name: deploy

on:
  push:
    tags:
    - '1.*'

jobs:
  package:
    runs-on: ubuntu-latest
    environment: conda-deploy
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: clonedSemicolon/setup-strace@v13
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
        miniforge-version: latest
        conda-solver: libmamba
        conda-remove-defaults: "true"
    - name: install build dependencies
      run: |
        conda install -n base -c conda-forge conda-build setuptools_scm anaconda-client -y
        conda config --set anaconda_upload yes
    - name: linux conda build and upload
      shell: bash -l {0}
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        xvfb-run --server-args="-screen 0 1024x768x24" \
        conda build -c pytorch -c nvidia -c ilastik-forge -c conda-forge \
        --user ilastik-forge \
        conda-recipe

    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
  trigger-release:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
    - name: trigger
      run: |
        echo "Triggering release pipeline!"
        curl \
          --silent \
          -X POST \
          -F token=${{ secrets.GL_TOKEN }} \
          -F "ref=main" \
          -F "variables[ILASTIK_VERSION]=${GITHUB_REF##*/}" \
          --output /dev/null \
          ${{ secrets.GL_URL }}
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
